# Use an official Mamba image as the base
FROM docker.io/mambaorg/micromamba:latest

# Switch to the root user to install packages and move things around
USER root

# Update package lists and install git
RUN apt-get update && apt-get install -y git-all

# Set the working directory in the container to /home/mambauser/app
WORKDIR /home/mambauser/app

# Clone the git repository in to the current working directory
RUN git clone https://github.com/NicholasCote/ERA5_interactive-cookbook-ncote.git

# Install packages specified in the repos environment.yml
# Activate this environment by providing ENV_NAME as an environment variable at runtime 
RUN micromamba env create -f ERA5_interactive-cookbook-ncote/environment.yml

# Move the notebook we are interested in to the current work directory
RUN mv ERA5_interactive-cookbook-ncote/notebooks/04_dashboard.ipynb .

# Remove files that are unneccessary
RUN rm -r ERA5_interactive-cookbook-ncote/

# Make port bokeh application port to the world outside this container
EXPOSE 5006

# Switch to mambauser so we are no longer on root
USER mambauser

# Run the command required to launch the notebook as a panel webserver
# The wildcard (*) used for allow-websocket-origin allows this to run on any address
# When using in production this should be scoped down to a URL or IP that will be used instead
CMD ["panel", "serve", "04_dashboard.ipynb", "--allow-websocket-origin=*", "--autoreload"]